controllers/AdminController.php
<?php

namespace app\controllers;

use Yii;
use yii\filters\AccessControl;
use yii\web\Controller;
use yii\filters\VerbFilter;
use app\models\LoginForm;
use app\models\ContactForm;
use yii\data\Pagination;
use app\models\Clients;
use app\models\UploadForm;
use yii\web\UploadedFile;

class AdminController extends \yii\web\Controller
{
	public $layout = 'admin';

	public function behaviors()
    {
        return [
            'access' => [
                'class' => AccessControl::className(),
                'only' => ['logout'],
                'rules' => [
                    [
                        'actions' => ['logout'],
                        'allow' => true,
                        'roles' => ['@'],
                    ],
                ],
            ],
            'verbs' => [
                'class' => VerbFilter::className(),
                'actions' => [
                    'logout' => ['post'],
                ],
            ],
        ];
    }

    /**
     * @inheritdoc
     */
    public function actions()
    {
        return [
            'error' => [
                'class' => 'yii\web\ErrorAction',
            ],
            'captcha' => [
                'class' => 'yii\captcha\CaptchaAction',
                'fixedVerifyCode' => YII_ENV_TEST ? 'testme' : null,
            ],
        ];
    }

    public function actionIndex()
    {
    	if (!Yii::$app->user->isGuest) {
            return $this->render('index');
        }

        $model = new LoginForm();
        if ($model->load(Yii::$app->request->post()) && $model->login()) {
            return $this->render('index');
        }
        return $this->render('login', [
            'model' => $model,
        ]);
        //return $this->render('index');
    }
    public function actionLogout()
    {
        Yii::$app->user->logout();

        return $this->goHome();
    }

    public function actionClients()
    {
    	$model = new \app\models\Clients;
        $query = $model->find();

        $pagination = new Pagination([
            'defaultPageSize' => 100,
            'totalCount' => $query->count(),
        ]);

        $clients = $query->orderBy('id')
            ->offset($pagination->offset)
            ->limit($pagination->limit)
            ->all();
        if(isset($_GET['add'])){
            $model = new \app\models\ClientsDataForm;
            if ($model->load(Yii::$app->request->post())) {
                if($model->addData()){
                    $model = new \app\models\Clients;
                    $query = $model->find();

                    $pagination = new Pagination([
                            'defaultPageSize' => 100,
                            'totalCount' => $query->count(),
                        ]);

                    $clients = $query->orderBy('id')
                        ->offset($pagination->offset)
                        ->limit($pagination->limit)
                        ->all();

                    return $this->render('clients', [
                        'clients' => $clients,
                        'pagination' => $pagination,
                    ]);
                }
            }
            return $this->render('ClientsData', [
                'model' => $model,
                'submitName' => 'Додати'
            ]);
        }else if(isset($_GET['edit'])){
            if(isset($_GET['id'])){
                $model = new \app\models\ClientsDataForm;
                if ($model->load(Yii::$app->request->post())) {
                    if($model->editData($_GET['id'])){
                        $model = new \app\models\Clients;
                        $query = $model->find();

                        $pagination = new Pagination([
                                'defaultPageSize' => 100,
                                'totalCount' => $query->count(),
                            ]);

                        $clients = $query->orderBy('id')
                            ->offset($pagination->offset)
                            ->limit($pagination->limit)
                            ->all();

                        return $this->render('clients', [
                            'clients' => $clients,
                            'pagination' => $pagination,
                        ]);
                    }
                }
                $clientData = $query->where(['id' => "{$_GET['id']}"])->one();
            
                return $this->render('ClientsData', [
                    'model' => $model,
                    'clientData' => $clientData,
                    'submitName' => 'Зберегти'
                ]);
            }else{
                return $this->render('clients', [
                        'clients' => $clients,
                        'pagination' => $pagination,
                    ]);
            }
        }else{
            return $this->render('clients', [
                'clients' => $clients,
                'pagination' => $pagination,
            ]);
        }
    }
    public function actionCategories()
    {
        $model = new \app\models\Categories;
        $query = $model->find();

        $pagination = new Pagination([
                'defaultPageSize' => 100,
                'totalCount' => $query->count(),
            ]);

        $categories = $query->orderBy('id')
            ->offset($pagination->offset)
            ->limit($pagination->limit)
            ->all();

        if(isset($_GET['add'])){
            $model = new \app\models\ProductsCategoriesDataForm;
            if ($model->load(Yii::$app->request->post())) {
                $model->image = UploadedFile::getInstance($model, 'image');
                if($model->addData()){
                    $model = new \app\models\Categories;
                    $query = $model->find();

                    $pagination = new Pagination([
                            'defaultPageSize' => 100,
                            'totalCount' => $query->count(),
                        ]);

                    $categories = $query->orderBy('id')
                        ->offset($pagination->offset)
                        ->limit($pagination->limit)
                        ->all();

                    return $this->render('categories', [
                        'categories' => $categories,
                        'pagination' => $pagination,
                    ]);
                }
            }
            return $this->render('ProductsCategoriesData', [
                'model' => $model,
                'categories' => $categories,
                'submitName' => 'Додати',
            ]);
        }else if(isset($_GET['edit'])){
            if(isset($_GET['id'])){
                $model = new \app\models\ProductsCategoriesDataForm;
                if ($model->load(Yii::$app->request->post())) {
                    $model->image = UploadedFile::getInstance($model, 'image');
                    if($model->editData($_GET['id'])){
                        $model = new \app\models\Categories;
                        $query = $model->find();

                        $pagination = new Pagination([
                                'defaultPageSize' => 100,
                                'totalCount' => $query->count(),
                            ]);

                        $categories = $query->orderBy('id')
                            ->offset($pagination->offset)
                            ->limit($pagination->limit)
                            ->all();

                        return $this->render('categories', [
                            'categories' => $categories,
                            'pagination' => $pagination,
                        ]);
                    }
                }
                $categoryData = $query->where(['id' => "{$_GET['id']}"])->one();
            
                return $this->render('ProductsCategoriesData', [
                    'model' => $model,
                    'categories' => $categories,
                    'categoryData' => $categoryData,
                    'submitName' => 'Зберегти',
                ]);
            }else{
                return $this->render('category', [
                        'category' => $categories,
                        'pagination' => $pagination,
                    ]);
            }
        }else{

            return $this->render('categories', [
                'categories' => $categories,
                'pagination' => $pagination,
            ]);
        }
    }
    public function actionProducts()
    {
        $modelUnits = new \app\models\Units;
        $queryUnits = $modelUnits->find();
        $units = $queryUnits->orderBy('id')
            ->all();

        foreach ($units as $unit) {
            $unitsName[$unit->id] = $unit->name;
        }

    	$modelCategories = new \app\models\Categories;
        $queryCategories = $modelCategories->find();
        $categories = $queryCategories->orderBy('id')
            ->all();

        foreach ($categories as $category) {
            $categoryName[$category->id] = $category->name;
        }

    	$modelProducts = new \app\models\Products;
    	$queryProducts = $modelProducts->find();

        $pagination = new Pagination([
            'defaultPageSize' => 100,
            'totalCount' => $queryProducts->count(),
        ]);

        $products = $queryProducts->orderBy('id')
            ->offset($pagination->offset)
            ->limit($pagination->limit)
            ->all();

        if(isset($_GET['add'])){
            $model = new \app\models\ProductsDataForm;
            if ($model->load(Yii::$app->request->post())) {
                $model->image = UploadedFile::getInstance($model, 'image');
                if($model->addData()){
                    $model = new \app\models\Products;
                    $query = $model->find();

                    $pagination = new Pagination([
                            'defaultPageSize' => 100,

views/layouts/admin.php
<?php

/* @var $this \yii\web\View */
/* @var $content string */

use yii\helpers\Html;
use yii\helpers\Url;
use yii\bootstrap\Nav;
use yii\bootstrap\NavBar;
use yii\widgets\Breadcrumbs;
use app\assets\AppAsset;

AppAsset::register($this);
?>
<?php $this->beginPage() ?>
<!DOCTYPE html>
<html lang="<?= Yii::$app->language ?>">
<head>
    <meta charset="<?= Yii::$app->charset ?>">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <?= Html::csrfMetaTags() ?>
    <title><?= Html::encode($this->title) ?></title>
    <link rel="shortcut icon" href="img/favicon.png">
    <?php $this->head() ?>
</head>
<body>
<?php $this->beginBody() ?>
    <!-- <div class="container">
        <?= Breadcrumbs::widget([
            'links' => isset($this->params['breadcrumbs']) ? $this->params['breadcrumbs'] : [],
        ]) ?>
    </div> -->
<div class="wrap">
<?php
    if (!Yii::$app->user->isGuest) {
        NavBar::begin([
            'brandLabel' => 'AeroKing',
            'brandUrl' => Yii::$app->homeUrl,
            'options' => [
                'class' => 'navbar-inverse navbar-fixed-top',
            ],
        ]);
        echo Nav::widget([
            'options' => ['class' => 'navbar-nav navbar-right'],
            'items' => [
                ['label' => 'Адмінка', 'url' => ['/admin/']],
                // ['label' => 'Налаштування', 'url' => ['/admin/settings']],
                ['label' => 'Заявки', 'url' => ['/admin/requests']],
                ['label' => 'Категорії товарів', 'url' => ['/admin/categories']],
                ['label' => 'Товари', 'url' => ['/admin/products']],
                ['label' => 'Покупці', 'url' => ['admin/clients']],
                ['label' => 'Відгуки', 'url' => ['/admin/comments']],
                Yii::$app->user->isGuest ? (
                    ['label' => 'Вхід', 'url' => ['/admin/login']]
                ) : (
                    '<li>'
                    . Html::beginForm(['/site/logout'], 'post')
                    . Html::submitButton(
                        'Вихід (' . Yii::$app->user->identity->username . ')',
                        ['class' => 'btn btn-link logout']
                    )
                    . Html::endForm()
                    . '</li>'
                )
            ],
        ]);
        NavBar::end();
    }
    ?>
    <div class="container"><?= $content ?></div>
</div>

<footer class="footer">
    <div class="container">
        <p class="pull-left">&copy; Webart <?= date('Y') ?></p>

        <p class="pull-right"><a href="http://webart-lviv.com.ua">Студія розробки та дизайну WebArt</a></p>
    </div>
</footer>

<?php $this->endBody() ?>
</body>
</html>
<?php $this->endPage() ?>